postgres_defaults: &postgres_defaults
  encoding: utf8
  template: template0
  host: localhost
  adapter: postgresql

development:
  <<: *postgres_defaults
  database: thatstyle
  username: <your computers username>
  password: iamthedefaultpassword

test:
  <<: *postgres_defaults
  database: thatstyle_test
  username: <your computers username>
  password: iamthedefaultpassword
